name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull jayaram/webapp:latest
            docker stop webapp || true
            docker rm webapp || true
            docker run -d -p 80:80 --name webapp jayaram/webapp:latest


