name: Rsync

on:
  push:
    branches:
      - dev

jobs:
  rsync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rsync
      run: sudo apt-get install -y rsync

    - name: Delay for 15 seconds
      run: sleep 15

    - name: Rsync via SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avz --exclude='.git' -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/CI-CD-WebApp-AutoDeploy

    - name: Rebuild and run Docker container
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/CI-CD-WebApp-AutoDeploy

          echo "Stopping old container"
          docker stop quizapp || true
          docker rm quizapp || true

          echo "Rebuilding Docker image"
          docker build -t quizapp .

          echo "Running new container on port 80"
          docker run -d -p 80:80 --name quizapp quizapp
        EOF
