name: Branch-Aware CI Pipeline

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main]

jobs:
  test-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests for dev
        run: echo "Running tests on DEV branch"

  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: echo "Deploying from MAIN branch"
